config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :todos do
    resource :complete, only: [:update], module: :todos
    resource :move, only: [:update], module: :todos
  end

  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  acts_as_list top_of_list: 0, add_new_to: :top

  scope :by_position, -> { order(position: :asc) }
  scope :complete, -> { where.not(completed_at: nil) }
  scope :incomplete, -> { where(completed_at: nil) }

  validates :title, presence: true

  def complete?
    completed_at?
  end

  def incomplete?
    !complete?
  end

  def toggle
    completed_at = (completed_at? ? nil : Time.current)
    position = Todo.incomplete.maximum(:position)

    # If it's already completed, add after the incomplete items
    # If it's not complete, we don't need to add 1, because
    # we're removing this item from the incomplete list
    position += 1 if completed_at?

    update(completed_at: completed_at, position: position)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos/completes_controller.rb
class Todos::CompletesController < ApplicationController
  before_action :set_todo

  def update
    @todo.toggle
    redirect_to root_path
  end

  private

  def set_todo
    @todo = Todo.find(params[:todo_id])
  end
end

app/controllers/todos/moves_controller.rb
class Todos::MovesController < ApplicationController
  before_action :set_todo

  def update
    @todo.insert_at(params[:index].to_i)
    head :ok
  end

  private

  def set_todo
    @todo = Todo.find(params[:todo_id])
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :destroy]

  def index
    @todos = Todo.all
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to root_path
    else
      @todos = Todo.all
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @todo.destroy
    redirect_to root_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 prose">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: todo do |form| %>
  <% if form.object.errors.any? %>
    <div>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <%= form.text_field :title, required: true, autofocus: true, placeholder: "What do you need to do?", class: "w-full" %>
  <%#= form.submit %>
<% end %>

app/views/todos/_todo.html.erb
<li class="group" draggable="<%= todo.incomplete? %>" data-action="drag->sort#drag dragend->sort#dragend" data-sort-url="<%= todo_move_path(todo) %>">
  <%= form_with model: todo, url: todo_complete_path(todo), class: "inline-block mt-0" do |form| %>
    <%= form.check_box :complete, checked: form.object.completed_at?, onchange: "this.form.requestSubmit()" %>
  <% end %>

  <%= todo.title %>

  <span class="ml-8">
    <%= link_to "Edit", edit_todo_path(todo), class: "hidden group-hover:inline" %>
    <%= button_to "Remove", todo_path(todo), method: :delete, data: {turbo_confirm: "Are you sure?"}, form_class: "inline-block mb-0", class: "hidden group-hover:inline" %>
  </span>
</li>

app/views/todos/edit.html.erb
<%= render "form", todo: @todo %>

app/views/todos/index.html.erb
<h1>My TodoList</h1>

<%= render "form", todo: @todo %>

<ul data-controller="sort" data-sort-active-class="opacity-50">
  <%= render @todos.by_position %>
</ul>